/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author lincbp
 */
public class Login extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private final String DATE_FORMAT = "yyyy-MM-dd";
    private final SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
        btnUserLogin.setVisible(false);
    }
    
    public void moveToRegister(){
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(siswaRegister);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
    public void moveToSiswaLogin(){
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        // Login Siswa
        contentPanel.add(siswaLogin);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
    public void moveToAdminLogin(){
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(adminLogin);
        contentPanel.repaint();
        contentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngJk = new javax.swing.ButtonGroup();
        btngGd = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUserLogin = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        siswaLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameInputSiswa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordInputSiswa = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        btnLoginToRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        siswaRegister = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        registerTempatLahir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        registerDob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        registerJk1 = new javax.swing.JRadioButton();
        registerJk2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        registerAgama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        registerGolDarA = new javax.swing.JRadioButton();
        registerGolDarB = new javax.swing.JRadioButton();
        registerGolDarAB = new javax.swing.JRadioButton();
        registerGolDarO = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        registerNisn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        registerNoTel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        registerEmail = new javax.swing.JTextField();
        btnRegisterBack = new javax.swing.JButton();
        btnsaveRegister = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        adminLogin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        usernameInputAdmin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        passwordInputAdmin = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ");

        btnUserLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Arrow_1.png"))); // NOI18N
        btnUserLogin.setText("Login Siswa");
        btnUserLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        btnAdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Arrow_1.png"))); // NOI18N
        btnAdminLogin.setText("Login Admin");
        btnAdminLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.png"))); // NOI18N
        jButton3.setText("EXIT");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(btnUserLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUserLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(btnAdminLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLoginToRegister.setText("Daftar");
        btnLoginToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginToRegisterActionPerformed(evt);
            }
        });

        jLabel4.setText("Username : NISN");

        jLabel5.setText("Password : Tanggal Lahir (yyyy-mm-dd) ");

        jLabel6.setText("NOTES : ");

        jLabel11.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        jLabel11.setText("Login Siswa");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout siswaLoginLayout = new javax.swing.GroupLayout(siswaLogin);
        siswaLogin.setLayout(siswaLoginLayout);
        siswaLoginLayout.setHorizontalGroup(
            siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siswaLoginLayout.createSequentialGroup()
                .addGroup(siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siswaLoginLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel14))
                    .addGroup(siswaLoginLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel11))
                    .addGroup(siswaLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(siswaLoginLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(siswaLoginLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoginToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(usernameInputSiswa)
                            .addComponent(passwordInputSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        siswaLoginLayout.setVerticalGroup(
            siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siswaLoginLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInputSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siswaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnLoginToRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        contentPanel.add(siswaLogin, "card2");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel7.setText("Nama Siswa");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel12.setText("Tempat Lahir");

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Lahir");

        jLabel16.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel16.setText("Jenis Kelamin");

        btngJk.add(registerJk1);
        registerJk1.setSelected(true);
        registerJk1.setText("Laki - Laki");
        registerJk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk1ActionPerformed(evt);
            }
        });

        btngJk.add(registerJk2);
        registerJk2.setText("Perempuan");
        registerJk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel17.setText("Agama");

        jLabel18.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel18.setText("Golongan Darah");

        btngGd.add(registerGolDarA);
        registerGolDarA.setSelected(true);
        registerGolDarA.setText("A");
        registerGolDarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerGolDarAActionPerformed(evt);
            }
        });

        btngGd.add(registerGolDarB);
        registerGolDarB.setText("B");

        btngGd.add(registerGolDarAB);
        registerGolDarAB.setText("AB");

        btngGd.add(registerGolDarO);
        registerGolDarO.setText("O");

        jLabel19.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel19.setText("NISN");

        registerNisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNisnKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel20.setText("Nomor Telpon");

        registerNoTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNoTelKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel21.setText("Email");

        btnRegisterBack.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        btnRegisterBack.setText("Kembali");
        btnRegisterBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterBackActionPerformed(evt);
            }
        });

        btnsaveRegister.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        btnsaveRegister.setText("Save");
        btnsaveRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerName)
                    .addComponent(registerTempatLahir)
                    .addComponent(registerDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerAgama)
                    .addComponent(registerNisn)
                    .addComponent(registerNoTel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerJk1)
                                .addGap(18, 18, 18)
                                .addComponent(registerJk2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerGolDarA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerGolDarB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registerGolDarAB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerGolDarO)))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addComponent(registerEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnRegisterBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsaveRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerTempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(registerJk1)
                    .addComponent(registerJk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(registerGolDarA)
                    .addComponent(registerGolDarB)
                    .addComponent(registerGolDarAB)
                    .addComponent(registerGolDarO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterBack)
                    .addComponent(btnsaveRegister))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel22.setText("REGISTER SISWA");

        javax.swing.GroupLayout siswaRegisterLayout = new javax.swing.GroupLayout(siswaRegister);
        siswaRegister.setLayout(siswaRegisterLayout);
        siswaRegisterLayout.setHorizontalGroup(
            siswaRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siswaRegisterLayout.createSequentialGroup()
                .addGroup(siswaRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siswaRegisterLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siswaRegisterLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel22)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        siswaRegisterLayout.setVerticalGroup(
            siswaRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siswaRegisterLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.add(siswaRegister, "card3");

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel9.setText("Username");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel10.setText("Password");

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        jLabel13.setText("Login Admin");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout adminLoginLayout = new javax.swing.GroupLayout(adminLogin);
        adminLogin.setLayout(adminLoginLayout);
        adminLoginLayout.setHorizontalGroup(
            adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addGroup(adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLoginLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel15))
                    .addGroup(adminLoginLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel13))
                    .addGroup(adminLoginLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addComponent(passwordInputAdmin)
                                .addComponent(jLabel9)
                                .addComponent(usernameInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        adminLoginLayout.setVerticalGroup(
            adminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLoginLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        contentPanel.add(adminLogin, "card2");

        jPanel3.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        btnUserLogin.setVisible(false);
        btnAdminLogin.setVisible(true);
        
        this.moveToSiswaLogin();
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        btnUserLogin.setVisible(true);
        btnAdminLogin.setVisible(false);
        
        this.moveToAdminLogin();
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnLoginToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginToRegisterActionPerformed
        // TODO add your handling code here:
        this.moveToRegister();
    }//GEN-LAST:event_btnLoginToRegisterActionPerformed

    private void registerJk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk1ActionPerformed

    private void registerJk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk2ActionPerformed

    private void registerGolDarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerGolDarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerGolDarAActionPerformed

    private void btnRegisterBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterBackActionPerformed
        // TODO add your handling code here:
        this.moveToSiswaLogin();
    }//GEN-LAST:event_btnRegisterBackActionPerformed
    
    private void btnsaveRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveRegisterActionPerformed
        // TODO add your handling code here:
        String nama = registerName.getText();
        String tempatLahir = registerTempatLahir.getText();
        String agama = registerAgama.getText();
        String nisn = registerNisn.getText();
        String noTelp = registerNoTel.getText();
        String email = registerEmail.getText();
        java.util.Date dob = java.sql.Date.valueOf(sdf.format(registerDob.getDate()));
        String jenisKel = "";
        if(registerJk1.isSelected()){
            jenisKel = "Laki - Laki";
        }
        if(registerJk2.isSelected()){
            jenisKel = "Perempuan";
        }
        
        String golDar = "";
        
        if(registerGolDarA.isSelected()){
            golDar = "A";
        }
        if(registerGolDarAB.isSelected()){
            golDar =  "AB";
        }
        if(registerGolDarB.isSelected()){
            golDar = "B";
        }
        
        if(registerGolDarO.isSelected()){
            golDar = "O";
        }
        boolean checkNisn = checknisn(nisn);
        
        if(checkNisn){
            String sql = "INSERT INTO siswa (nama, jenis_kelamin, agama, golongan_darah, tanggal_lahir, nisn, tempat_lahir, nomor_telpon, email) VALUES (?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jenisKel);
                stat.setString(3, agama);
                stat.setString(4, golDar);
                stat.setDate(5, new java.sql.Date(dob.getTime()));
                stat.setString(6, nisn);
                stat.setString(7, tempatLahir);
                stat.setString(8, noTelp);
                stat.setString(9, email);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil");
                reset();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }
        
        
        
    }//GEN-LAST:event_btnsaveRegisterActionPerformed

    private void registerNoTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNoTelKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNoTelKeyTyped

    private void registerNisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNisnKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNisnKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = usernameInputSiswa.getText();
        String password = passwordInputSiswa.getText();
        int checkLogin = loginSiswa(username, password);
        if(checkLogin > 0){
            JOptionPane.showMessageDialog(null, "Login Berhasil");
            new MainMenu("siswa",checkLogin).setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Login Gagal");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username = usernameInputAdmin.getText();
        String password = passwordInputAdmin.getText();
        int checkLogin = loginAdmin(username, password);
        
        if(checkLogin > 0){
            JOptionPane.showMessageDialog(null, "Login Berhasil");
            new MainMenu("admin", checkLogin).setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Login Gagal");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
   public int loginSiswa(String username,String password){
       int res = 0;
       String sql = "SELECT * FROM siswa WHERE nisn='"+username+"' AND tanggal_lahir='"+password+"'";
         try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                res = rs.getInt("id_siswa");
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
       return res;
   }
   
   public int loginAdmin(String username,String password){
       int res = 0;
       String sql = "SELECT * FROM admin WHERE username='"+username+"' AND password='"+password+"'";
         try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                res = rs.getInt("id_user");
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
       return res;
   }
    
//    public boolean loginSiswa(String username, String password){
//        boolean res = false;
//        String sql = "SELECT * FROM siswa WHERE nisn='"+username+"' AND tanggal_lahir='"+password+"'";
//         try{
//            java.sql.Statement stat = conn.createStatement();
//            ResultSet rs = stat.executeQuery(sql);
//            if(rs.next()){
//                res = true;
//            }
//        }catch (SQLException e){
//            e.printStackTrace();
//        }
//        return res;
//    }
    public boolean checknisn(String nisn){
        boolean res = true;
        String sql = "SELECT * FROM siswa WHERE nisn ='"+nisn+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                res = false;
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
        return res;
    }
    
    public void reset(){
        registerAgama.setText("");
        registerTempatLahir.setText("");
        registerName.setText("");
        registerNisn.setText("");
        registerNoTel.setText("");
        registerEmail.setText("");
        btngGd.clearSelection();
        btngJk.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminLogin;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnLoginToRegister;
    private javax.swing.JButton btnRegisterBack;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.ButtonGroup btngGd;
    private javax.swing.ButtonGroup btngJk;
    private javax.swing.JButton btnsaveRegister;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passwordInputAdmin;
    private javax.swing.JPasswordField passwordInputSiswa;
    private javax.swing.JTextField registerAgama;
    private com.toedter.calendar.JDateChooser registerDob;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JRadioButton registerGolDarA;
    private javax.swing.JRadioButton registerGolDarAB;
    private javax.swing.JRadioButton registerGolDarB;
    private javax.swing.JRadioButton registerGolDarO;
    private javax.swing.JRadioButton registerJk1;
    private javax.swing.JRadioButton registerJk2;
    private javax.swing.JTextField registerName;
    private javax.swing.JTextField registerNisn;
    private javax.swing.JTextField registerNoTel;
    private javax.swing.JTextField registerTempatLahir;
    private javax.swing.JPanel siswaLogin;
    private javax.swing.JPanel siswaRegister;
    private javax.swing.JTextField usernameInputAdmin;
    private javax.swing.JTextField usernameInputSiswa;
    // End of variables declaration//GEN-END:variables
}
