/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author lincbp
 */
public class masterSiswa extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private int selectedId;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form masterSiswa
     */
    public masterSiswa() {
        initComponents();
        btnUpdate.setVisible(false);
        btnHapus.setVisible(false);
        btnReset.setVisible(false);
        this.initTable();
    }   

    public void initTable(){
        Object[] Baris={"Id","Nama","Jenis Kelamin","Agama","Golongan Darah","Tanggal Lahir","Tempat Lahir","NISN","No. Telp","Email"};
        tabmode = new DefaultTableModel(null, Baris);
        tableSiswa.setModel(tabmode);   
        
        String sql = "select * from siswa";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                int a = hasil.getInt("id_siswa");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("agama");
                String e = hasil.getString("golongan_darah");
                String f = hasil.getString("tanggal_lahir");
                String g = hasil.getString("tempat_lahir");
                String h = hasil.getString("nisn");
                String i = hasil.getString("nomor_telpon");
                String j = hasil.getString("email");

                Object[] data={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        bgJk = new javax.swing.ButtonGroup();
        bgGolDar = new javax.swing.ButtonGroup();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        registerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registerTempatLahir = new javax.swing.JTextField();
        registerDob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        registerJk2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        registerJk1 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        registerAgama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        registerGolDarO = new javax.swing.JRadioButton();
        registerGolDarAB = new javax.swing.JRadioButton();
        registerGolDarA = new javax.swing.JRadioButton();
        registerGolDarB = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        registerNisn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        registerNoTel = new javax.swing.JTextField();
        registerEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();

        jCheckBox1.setText("jCheckBox1");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel7.setText("Nama Siswa");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel12.setText("Tempat Lahir");

        registerTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTempatLahirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Lahir");

        bgJk.add(registerJk2);
        registerJk2.setText("Perempuan");
        registerJk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel16.setText("Jenis Kelamin");

        bgJk.add(registerJk1);
        registerJk1.setSelected(true);
        registerJk1.setText("Laki - Laki");
        registerJk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel17.setText("Agama");

        jLabel18.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel18.setText("Golongan Darah");

        bgGolDar.add(registerGolDarO);
        registerGolDarO.setText("O");

        bgGolDar.add(registerGolDarAB);
        registerGolDarAB.setText("AB");

        bgGolDar.add(registerGolDarA);
        registerGolDarA.setSelected(true);
        registerGolDarA.setText("A");
        registerGolDarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerGolDarAActionPerformed(evt);
            }
        });

        bgGolDar.add(registerGolDarB);
        registerGolDarB.setText("B");

        jLabel19.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel19.setText("NISN");

        registerNisn.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                registerNisnInputMethodTextChanged(evt);
            }
        });
        registerNisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNisnKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel20.setText("Nomor Telpon");

        jLabel21.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel21.setText("Email");

        registerNoTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNoTelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerTempatLahir)
                            .addComponent(registerName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerNisn)
                            .addComponent(registerAgama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerJk1)
                                .addGap(18, 18, 18)
                                .addComponent(registerJk2)
                                .addContainerGap(247, Short.MAX_VALUE))
                            .addComponent(registerNoTel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerGolDarA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerGolDarB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(registerGolDarAB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerGolDarO)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(registerEmail)
                            .addComponent(registerDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerName, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(registerDob, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(registerJk1)
                    .addComponent(registerJk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerGolDarA)
                    .addComponent(registerGolDarB)
                    .addComponent(registerGolDarAB)
                    .addComponent(registerGolDarO)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerNoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerJk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk1ActionPerformed

    private void registerJk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk2ActionPerformed

    private void registerGolDarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerGolDarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerGolDarAActionPerformed

    private void registerNisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNisnKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNisnKeyTyped

    private void registerNoTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNoTelKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNoTelKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama = registerName.getText();
        String tempatLahir = registerTempatLahir.getText();
        String agama = registerAgama.getText();
        String nisn = registerNisn.getText();
        String noTelp = registerNoTel.getText();
        String email = registerEmail.getText();
        java.util.Date dob = java.sql.Date.valueOf(sdf.format(registerDob.getDate()));
        String jenisKel = "";
        if(registerJk1.isSelected()){
            jenisKel = "Laki - Laki";
        }
        if(registerJk2.isSelected()){
            jenisKel = "Perempuan";
        }
        
        String golDar = "";
        
        if(registerGolDarA.isSelected()){
            golDar = "A";
        }
        if(registerGolDarAB.isSelected()){
            golDar =  "AB";
        }
        if(registerGolDarB.isSelected()){
            golDar = "B";
        }
        
        if(registerGolDarO.isSelected()){
            golDar = "O";
        }
        boolean checkNisn = checknisn(nisn,0);
        if(checkNisn){
            String sql = "INSERT INTO siswa (nama, jenis_kelamin, agama, golongan_darah, tanggal_lahir, nisn, tempat_lahir, nomor_telpon, email) VALUES (?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jenisKel);
                stat.setString(3, agama);
                stat.setString(4, golDar);
                stat.setDate(5, new java.sql.Date(dob.getTime()));
                stat.setString(6, nisn);
                stat.setString(7, tempatLahir);
                stat.setString(8, noTelp);
                stat.setString(9, email);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                reset();
                initTable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }else{
          JOptionPane.showMessageDialog(null, "Duplikat NISN");  
        }
    }//GEN-LAST:event_btnTambahActionPerformed
    public boolean checknisn(String nisn,int id){
        boolean res = true;
        String sql = "SELECT * FROM siswa WHERE nisn ='"+nisn+"'";
        if(id > 0){
            sql += "AND id_siswa != '"+id+"'";
        }
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                res = false;
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
        return res;
    }
    public void reset(){
        registerAgama.setText("");
        registerTempatLahir.setText("");
        registerName.setText("");
        registerNisn.setText("");
        registerNoTel.setText("");
        registerEmail.setText("");
        registerDob.setDate(null);
        btnUpdate.setVisible(false);
        btnHapus.setVisible(false);
        btnReset.setVisible(false);
        btnTambah.setVisible(true);
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String nama = registerName.getText();
        String tempatLahir = registerTempatLahir.getText();
        String agama = registerAgama.getText();
        String nisn = registerNisn.getText();
        String noTelp = registerNoTel.getText();
        String email = registerEmail.getText();
        java.util.Date dob = java.sql.Date.valueOf(sdf.format(registerDob.getDate()));
        String jenisKel = "";
        if(registerJk1.isSelected()){
            jenisKel = "Laki - Laki";
        }
        if(registerJk2.isSelected()){
            jenisKel = "Perempuan";
        }
        
        String golDar = "";
        
        if(registerGolDarA.isSelected()){
            golDar = "A";
        }
        if(registerGolDarAB.isSelected()){
            golDar =  "AB";
        }
        if(registerGolDarB.isSelected()){
            golDar = "B";
        }
        
        if(registerGolDarO.isSelected()){
            golDar = "O";
        }
        boolean checkNisn = checknisn(nisn,selectedId);
        if(checkNisn){
            String sql = "UPDATE siswa SET nama=?, jenis_kelamin=?, agama=?, golongan_darah=?, tanggal_lahir=?, nisn=?, tempat_lahir=?, nomor_telpon=?, email=? WHERE id_siswa=?";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jenisKel);
                stat.setString(3, agama);
                stat.setString(4, golDar);
                stat.setDate(5, new java.sql.Date(dob.getTime()));
                stat.setString(6, nisn);
                stat.setString(7, tempatLahir);
                stat.setString(8, noTelp);
                stat.setString(9, email);
                stat.setInt(10, selectedId);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil DiUpdate");
                initTable();
                reset();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        }else{
          JOptionPane.showMessageDialog(null, "Duplikat NISN");  
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
//        // TODO add your handling code here:
        String sql = "DELETE FROM siswa WHERE id_siswa = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, selectedId);

            int rowsAffected = stat.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                initTable();
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void registerTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerTempatLahirActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        // TODO add your handling code here:

        int row = tableSiswa.getSelectedRow();

        if(row != -1){
            selectedId = Integer.valueOf(tableSiswa.getValueAt(row, 0).toString());
            String nama = tableSiswa.getValueAt(row, 1).toString();
            String jenis_kelamin = tableSiswa.getValueAt(row, 2).toString();
            String agama = tableSiswa.getValueAt(row, 3).toString();
            String golongan_darah = tableSiswa.getValueAt(row, 4).toString();
            String tanggal_lahir = tableSiswa.getValueAt(row, 5).toString();
            String tempat_lahir = tableSiswa.getValueAt(row, 6).toString();
            String nisn = tableSiswa.getValueAt(row, 7).toString();
            String nomor_telpon = tableSiswa.getValueAt(row, 8).toString();
            String email = tableSiswa.getValueAt(row, 9).toString();

            java.util.Date reformatDate = null;
            
            try{
                reformatDate = sdf.parse(tanggal_lahir);
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
            registerName.setText(nama);
            registerTempatLahir.setText(tempat_lahir);
            registerAgama.setText(agama);
            registerNisn.setText(nisn);
            registerNoTel.setText(nomor_telpon);
            registerEmail.setText(email);
            registerDob.setDate(reformatDate);
            if(jenis_kelamin.equals("Perempuan")){
                registerJk2.setSelected(true);
            }else{
                registerJk1.setSelected(true);
            }
            
            if(golongan_darah.equals("A")){
                registerGolDarA.setSelected(true);
            }
            if(golongan_darah.equals("AB")){
                registerGolDarAB.setSelected(true);
            }
            if(golongan_darah.equals("B")){
                registerGolDarB.setSelected(true);
            }
            if(golongan_darah.equals("O")){
                registerGolDarO.setSelected(true);
            }
            
            btnTambah.setVisible(false);
            btnUpdate.setVisible(true);
            btnHapus.setVisible(true);
            btnReset.setVisible(true);
        }
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void registerNisnInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_registerNisnInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_registerNisnInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGolDar;
    private javax.swing.ButtonGroup bgJk;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField registerAgama;
    private com.toedter.calendar.JDateChooser registerDob;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JRadioButton registerGolDarA;
    private javax.swing.JRadioButton registerGolDarAB;
    private javax.swing.JRadioButton registerGolDarB;
    private javax.swing.JRadioButton registerGolDarO;
    private javax.swing.JRadioButton registerJk1;
    private javax.swing.JRadioButton registerJk2;
    private javax.swing.JTextField registerName;
    private javax.swing.JTextField registerNisn;
    private javax.swing.JTextField registerNoTel;
    private javax.swing.JTextField registerTempatLahir;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables
}
