/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author lincbp
 */
public class MasterSiswa extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private int selectedId;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form masterSiswa
     */
    public MasterSiswa() {
        initComponents();
        btnUpdate.setVisible(false);
        btnHapus.setVisible(false);
        this.initTable();
    }   
    
    public void moveToTable(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelTable);
        cardLayout.repaint();
        cardLayout.revalidate();
    }
    
    public void moveToForm(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelForm);
        cardLayout.repaint();
        cardLayout.revalidate();
    }

    public void initTable(){
        Object[] Baris={"Id","Nama","Jenis Kelamin","Agama","Golongan Darah","Tanggal Lahir","Tempat Lahir","NISN","No. Telp","Email"};
        tabmode = new DefaultTableModel(null, Baris);
        tableSiswa.setModel(tabmode);   
        
        String sql = "select * from siswa";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                int a = hasil.getInt("id_siswa");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("agama");
                String e = hasil.getString("golongan_darah");
                String f = hasil.getString("tanggal_lahir");
                String g = hasil.getString("tempat_lahir");
                String h = hasil.getString("nisn");
                String i = hasil.getString("nomor_telpon");
                String j = hasil.getString("email");

                Object[] data={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        bgJk = new javax.swing.ButtonGroup();
        bgGolDar = new javax.swing.ButtonGroup();
        cardLayout = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        registerNoTel = new javax.swing.JTextField();
        registerAgama = new javax.swing.JTextField();
        registerEmail = new javax.swing.JTextField();
        registerName = new javax.swing.JTextField();
        registerGolDarO = new javax.swing.JRadioButton();
        registerGolDarAB = new javax.swing.JRadioButton();
        registerTempatLahir = new javax.swing.JTextField();
        registerGolDarA = new javax.swing.JRadioButton();
        registerGolDarB = new javax.swing.JRadioButton();
        registerJk2 = new javax.swing.JRadioButton();
        registerNisn = new javax.swing.JTextField();
        registerJk1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registerDob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFormSave = new javax.swing.JButton();
        btnFormUpdate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setLayout(new java.awt.CardLayout());

        cardLayout.setLayout(new java.awt.CardLayout());

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari");

        jButton3.setText("Cari");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel2.setText("Data Master Siswa");

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableSiswa);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTableLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addComponent(jLabel2)
                            .addGroup(panelTableLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(0, 686, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(146, 146, 146))
        );

        cardLayout.add(panelTable, "card3");

        panelForm.setLayout(new javax.swing.BoxLayout(panelForm, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 568));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        panelForm.add(jPanel4);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("FORM SISWA");

        registerNoTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNoTelKeyTyped(evt);
            }
        });

        registerAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAgamaActionPerformed(evt);
            }
        });

        bgGolDar.add(registerGolDarO);
        registerGolDarO.setText("O");

        bgGolDar.add(registerGolDarAB);
        registerGolDarAB.setText("AB");

        registerTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTempatLahirActionPerformed(evt);
            }
        });

        bgGolDar.add(registerGolDarA);
        registerGolDarA.setSelected(true);
        registerGolDarA.setText("A");
        registerGolDarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerGolDarAActionPerformed(evt);
            }
        });

        bgGolDar.add(registerGolDarB);
        registerGolDarB.setText("B");

        bgJk.add(registerJk2);
        registerJk2.setText("Perempuan");
        registerJk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk2ActionPerformed(evt);
            }
        });

        registerNisn.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                registerNisnInputMethodTextChanged(evt);
            }
        });
        registerNisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerNisnKeyTyped(evt);
            }
        });

        bgJk.add(registerJk1);
        registerJk1.setSelected(true);
        registerJk1.setText("Laki - Laki");
        registerJk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJk1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Siswa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tempat Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Agama");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Golongan Darah");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("NISN");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("No Telpon");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Email");

        btnFormSave.setText("Save");
        btnFormSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSaveActionPerformed(evt);
            }
        });

        btnFormUpdate.setText("Update");
        btnFormUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUpdateActionPerformed(evt);
            }
        });

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 579, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerAgama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerNisn)
                            .addComponent(registerNoTel)
                            .addComponent(registerEmail)
                            .addComponent(registerTempatLahir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(registerJk1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(registerJk2))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(registerGolDarA)
                                        .addGap(18, 18, 18)
                                        .addComponent(registerGolDarB)
                                        .addGap(18, 18, 18)
                                        .addComponent(registerGolDarAB)
                                        .addGap(18, 18, 18)
                                        .addComponent(registerGolDarO)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFormUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFormSave))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(registerDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(registerJk1)
                    .addComponent(registerJk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(registerAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(registerGolDarA)
                    .addComponent(registerGolDarB)
                    .addComponent(registerGolDarAB)
                    .addComponent(registerGolDarO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(registerNisn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(registerNoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSave)
                    .addComponent(btnFormUpdate)
                    .addComponent(jButton4))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        panelForm.add(mainPanel);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 568));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        panelForm.add(jPanel5);

        cardLayout.add(panelForm, "card4");

        add(cardLayout, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void registerJk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk1ActionPerformed

    private void registerJk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJk2ActionPerformed

    private void registerGolDarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerGolDarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerGolDarAActionPerformed

    private void registerNisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNisnKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNisnKeyTyped

    private void registerNoTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerNoTelKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_registerNoTelKeyTyped
    public boolean checknisn(String nisn,int id){
        boolean res = true;
        String sql = "SELECT * FROM siswa WHERE nisn ='"+nisn+"'";
        if(id > 0){
            sql += "AND id_siswa != '"+id+"'";
        }
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                res = false;
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
        return res;
    }
    public void reset(){
        registerAgama.setText("");
        registerTempatLahir.setText("");
        registerName.setText("");
        registerNisn.setText("");
        registerNoTel.setText("");
        registerEmail.setText("");
        registerDob.setDate(null);
        btnUpdate.setVisible(false);
        btnHapus.setVisible(false);
        btnTambah.setVisible(true);
        
        tableSiswa.clearSelection();
        selectedId = 0;
    }
    private void registerTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerTempatLahirActionPerformed

    private void registerNisnInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_registerNisnInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_registerNisnInputMethodTextChanged

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        this.moveToForm();
        btnFormUpdate.setVisible(false);
        btnFormSave.setVisible(true);
        this.reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.moveToForm();

        btnFormUpdate.setVisible(true);
        btnFormSave.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String search = "'%"+searchTxt.getText()+"%'";
        Object[] Baris={"Id","Nama","Jenis Kelamin","Agama","Golongan Darah","Tanggal Lahir","Tempat Lahir","NISN","No. Telp","Email"};
        tabmode = new DefaultTableModel(null, Baris);
        tableSiswa.setModel(tabmode);

        String sql = "SELECT * FROM siswa WHERE nama LIKE " +search+" OR nisn LIKE "+search;
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                 int a = hasil.getInt("id_siswa");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("agama");
                String e = hasil.getString("golongan_darah");
                String f = hasil.getString("tanggal_lahir");
                String g = hasil.getString("tempat_lahir");
                String h = hasil.getString("nisn");
                String i = hasil.getString("nomor_telpon");
                String j = hasil.getString("email");

                Object[] data={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM siswa WHERE id_siswa = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, selectedId);

            int rowsAffected = stat.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                initTable();
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed
 
    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        // TODO add your handling code here:
        int row = tableSiswa.getSelectedRow();
        
        if(row != -1){
            
            if(selectedId > 0 && selectedId == Integer.valueOf(tableSiswa.getValueAt(row, 0).toString())){
                this.reset();
            }else{
                String nama = tableSiswa.getValueAt(row, 1).toString();
                String jk = tableSiswa.getValueAt(row, 2).toString();
                String agama = tableSiswa.getValueAt(row, 3).toString();
                String golDar = tableSiswa.getValueAt(row, 4).toString();
                String tanggalLahir = tableSiswa.getValueAt(row, 5).toString();
                String tempatLahir = tableSiswa.getValueAt(row, 6).toString();
                String nisn = tableSiswa.getValueAt(row, 7).toString();
                String noTelp = tableSiswa.getValueAt(row, 8).toString();
                String email = tableSiswa.getValueAt(row, 9).toString();
                selectedId = Integer.valueOf(tableSiswa.getValueAt(row, 0).toString());

                registerName.setText(nama);
                registerAgama.setText(agama);
                registerNisn.setText(nisn);
                registerEmail.setText(email);
                registerNoTel.setText(noTelp);
                registerTempatLahir.setText(tempatLahir);
                if(jk.equals("Laki - Laki")){
                    registerJk1.setSelected(true);
                }else{
                    registerJk2.setSelected(true);
                }

                if(golDar.equals("A")){
                    registerGolDarA.setSelected(true);
                }
                if(golDar.equals("B")){
                    registerGolDarB.setSelected(true);
                }
                if(golDar.equals("AB")){
                    registerGolDarAB.setSelected(true);
                }
                if(golDar.equals("O")){
                    registerGolDarO.setSelected(true);
                }
                java.util.Date dobFormat = null;
                try{
                    dobFormat = sdf.parse(tanggalLahir);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                registerDob.setDate(dobFormat);

                btnTambah.setVisible(false);
                btnUpdate.setVisible(true);
                btnHapus.setVisible(true);
            }
//            btnReset.setVisible(true);
        }
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void registerAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerAgamaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.moveToTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnFormSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSaveActionPerformed
        // TODO add your handling code here:
        if(validateInput()){
            String nama = registerName.getText();
            String tempatLahir = registerTempatLahir.getText();
            String agama = registerAgama.getText();
            String nisn = registerNisn.getText();
            String noTelp = registerNoTel.getText();
            String email = registerEmail.getText();
            java.util.Date dob = java.sql.Date.valueOf(sdf.format(registerDob.getDate()));
            String jenisKel = "";
            if(registerJk1.isSelected()){
                jenisKel = "Laki - Laki";
            }
            if(registerJk2.isSelected()){
                jenisKel = "Perempuan";
            }

            String golDar = "";

            if(registerGolDarA.isSelected()){
                golDar = "A";
            }
            if(registerGolDarAB.isSelected()){
                golDar =  "AB";
            }
            if(registerGolDarB.isSelected()){
                golDar = "B";
            }

            if(registerGolDarO.isSelected()){
                golDar = "O";
            }

            String sql = "INSERT INTO siswa (nama, jenis_kelamin, agama, golongan_darah, tanggal_lahir, nisn, tempat_lahir, nomor_telpon, email) VALUES (?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jenisKel);
                stat.setString(3, agama);
                stat.setString(4, golDar);
                stat.setDate(5, new java.sql.Date(dob.getTime()));
                stat.setString(6, nisn);
                stat.setString(7, tempatLahir);
                stat.setString(8, noTelp);
                stat.setString(9, email);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil");
                reset();
                this.initTable();
                this.moveToTable();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        
        }
    }//GEN-LAST:event_btnFormSaveActionPerformed

    private void btnFormUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUpdateActionPerformed
        // TODO add your handling code here:
        
        if(validateInput()){
            String nama = registerName.getText();
            String tempatLahir = registerTempatLahir.getText();
            String agama = registerAgama.getText();
            String nisn = registerNisn.getText();
            String noTelp = registerNoTel.getText();
            String email = registerEmail.getText();
            java.util.Date dob = java.sql.Date.valueOf(sdf.format(registerDob.getDate()));
            String jenisKel = "";
            if(registerJk1.isSelected()){
                jenisKel = "Laki - Laki";
            }
            if(registerJk2.isSelected()){
                jenisKel = "Perempuan";
            }

            String golDar = "";

            if(registerGolDarA.isSelected()){
                golDar = "A";
            }
            if(registerGolDarAB.isSelected()){
                golDar =  "AB";
            }
            if(registerGolDarB.isSelected()){
                golDar = "B";
            }

            if(registerGolDarO.isSelected()){
                golDar = "O";
            }

            String sql = "UPDATE siswa SET nama=?, jenis_kelamin=?, agama=?, golongan_darah=?, tanggal_lahir=?, nisn=?, tempat_lahir=?, nomor_telpon=?, email=? WHERE id_siswa=?";
//            String sql = "INSERT INTO siswa (nama, jenis_kelamin, agama, golongan_darah, tanggal_lahir, nisn, tempat_lahir, nomor_telpon, email) VALUES (?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, jenisKel);
                stat.setString(3, agama);
                stat.setString(4, golDar);
                stat.setDate(5, new java.sql.Date(dob.getTime()));
                stat.setString(6, nisn);
                stat.setString(7, tempatLahir);
                stat.setString(8, noTelp);
                stat.setString(9, email);
                stat.setInt(10, selectedId);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil");
                reset();
                this.initTable();
                this.moveToTable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
            }
        
        }
    }//GEN-LAST:event_btnFormUpdateActionPerformed
    
    private boolean validateInput(){
        boolean res = true;
        String response = "";
        if(registerName.getText().equals("")){
            res = false;
            response += "Nama Wajib Diisi \n";
        }
        
        if(registerTempatLahir.getText().equals("")){
            res = false;
            response += "Tempat Lahir Wajib Diisi \n";
        }
        
        if(registerDob.getDate() == null){
            res = false;
            response += "Tanggal Lahir Wajib Diisi \n";
        }
        
        if(!registerJk1.isSelected() && !registerJk2.isSelected()){
            res = false;
            response += "Jenis Kelamin Wajib Dipilih \n";
        }
        
        if(registerAgama.getText().equals("")){
            res = false;
            response += "Agama Wajib Diisi \n";
        }
        
        if(!registerGolDarA.isSelected() && !registerGolDarAB.isSelected() && !registerGolDarB.isSelected() && !registerGolDarO.isSelected()){
            res = false;
            response += "Golongan Darah Wajib Dipilih \n";
        }
        
        if(registerNisn.getText().equals("")){
            res = false;
            response += "NISN Wajib Diisi \n";
        }
        
        if(registerNoTel.getText().equals("")){
            res = false;
            response += "Nomor Telpon Wajib Diisi \n";
        }
        
        if(registerNisn.getText().equals("")){
            res = false;
            response += "NISN Wajib Diisi \n";
            
            if(this.checknisn(registerNisn.getText(), selectedId)){
                res = false;
                response += "NISN sudah ada \n";
            }
        }
        
        if(registerNoTel.getText().equals("")){
            res = false;
            response += "Nomor Telpon Wajib Diisi \n";
        }
        
        if(registerEmail.getText().equals("")){
            res = false;
            response += "Email Wajib Diisi \n";
        }
        
        if(!response.equals("")){
            JOptionPane.showMessageDialog(null, response);
        }
        
        return res;
    }
    
    public void insert(){
        try{
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGolDar;
    private javax.swing.ButtonGroup bgJk;
    private javax.swing.JButton btnFormSave;
    private javax.swing.JButton btnFormUpdate;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTextField registerAgama;
    private com.toedter.calendar.JDateChooser registerDob;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JRadioButton registerGolDarA;
    private javax.swing.JRadioButton registerGolDarAB;
    private javax.swing.JRadioButton registerGolDarB;
    private javax.swing.JRadioButton registerGolDarO;
    private javax.swing.JRadioButton registerJk1;
    private javax.swing.JRadioButton registerJk2;
    private javax.swing.JTextField registerName;
    private javax.swing.JTextField registerNisn;
    private javax.swing.JTextField registerNoTel;
    private javax.swing.JTextField registerTempatLahir;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables
}
