/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author lincbp
 */
public class NilaiSiswa extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private int selectedId;
    private int idPendaftaran;
    private String statusPendaftaran;
    
    private int nilaiRataRata;
    private int totalNilai;
    /**
     * Creates new form masterJurusan
     */
    public NilaiSiswa(int idPendaftaran,String status) {
        initComponents();
        this.idPendaftaran = idPendaftaran;
        btnUpdate.setVisible(false);
        btnHapus.setVisible(false);
        
        this.statusPendaftaran = status;
        
        if(!statusPendaftaran.equals("Baru")){
            btnUpdate.setVisible(false);
            btnHapus.setVisible(false);
            btnTambah.setVisible(false);
        }
//        btnReset.setVisible(false);
        this.initTable();
        
    }
    
    public void moveToTable(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelTable);
        cardLayout.repaint();
        cardLayout.revalidate();
    }
    
    public void moveToForm(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelForm);
        cardLayout.repaint();
        cardLayout.revalidate();
    }
    public void initTable(){
        Object[] Baris={"Id","Nama Mata Pelajaran","Nilai"};
        tabmode = new DefaultTableModel(null, Baris);
        tableJurusan.setModel(tabmode);
        nilaiRataRata = 0;
        totalNilai = 0;
        
        String sql = "select * from nilai where id_pendaftaran = '"+idPendaftaran+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                int a = hasil.getInt("id_nilai");
                String b = hasil.getString("nama_jenis");
                String c = hasil.getString("nilai");
                
                nilaiRataRata += hasil.getInt("nilai");
                totalNilai++;
                
                Object[] data={a,b,c};
                tabmode.addRow(data);
            }
            if(totalNilai == 0){
                totalNilai = 1;
            }
            Double nilaiView = Double.valueOf(nilaiRataRata/totalNilai);
            nilaiRata.setText("Nilai Rata - Rata : "+nilaiView.toString());
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    public void reset(){
        namaTxt.setText("");
        nilaiTxt.setText("");
        System.out.println(statusPendaftaran);
        if(!statusPendaftaran.equals("Baru")){
            btnUpdate.setVisible(false);
            btnHapus.setVisible(false);
            btnTambah.setVisible(false);
        }else{
            btnTambah.setVisible(true);
            btnUpdate.setVisible(false);
            btnHapus.setVisible(false);
            
        }
        
        tableJurusan.clearSelection();
        selectedId = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLayout = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJurusan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nilaiRata = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        btnFormSave = new javax.swing.JButton();
        btnFormUpdate = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nilaiTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        cardLayout.setLayout(new java.awt.CardLayout());

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJurusan);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel2.setText("Nilai Siswa");

        nilaiRata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nilaiRata.setText("jLabel1");

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nilaiRata)))
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nilaiRata))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );

        cardLayout.add(panelTable, "card2");

        panelForm.setLayout(new javax.swing.BoxLayout(panelForm, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 485));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        panelForm.add(jPanel2);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Mata Pelajaran");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nilai");

        btnFormSave.setText("Save");
        btnFormSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSaveActionPerformed(evt);
            }
        });

        btnFormUpdate.setText("Update");
        btnFormUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUpdateActionPerformed(evt);
            }
        });

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("FORM NILAI SISWA");

        nilaiTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilaiTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nilaiTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFormUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFormSave))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nilaiTxt)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nilaiTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSave)
                    .addComponent(btnFormUpdate)
                    .addComponent(backBtn))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        panelForm.add(mainPanel);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 485));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        panelForm.add(jPanel3);

        cardLayout.add(panelForm, "card3");

        add(cardLayout, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        this.moveToForm();
        btnFormUpdate.setVisible(false);
        btnFormSave.setVisible(true);
        this.reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJurusanMouseClicked
        // TODO add your handling code here:
        int row = tableJurusan.getSelectedRow();
        
        if(row != -1 && statusPendaftaran.equals("Baru")){
            if(selectedId > 0 && selectedId == Integer.valueOf(tableJurusan.getValueAt(row, 0).toString())){
                this.reset();
            }else{
                String nama = tableJurusan.getValueAt(row, 1).toString();
                String keterangan = tableJurusan.getValueAt(row, 2).toString();
                selectedId = Integer.valueOf(tableJurusan.getValueAt(row, 0).toString());

                namaTxt.setText(nama);
                nilaiTxt.setText(keterangan);
                btnTambah.setVisible(false);
                btnUpdate.setVisible(true);
                btnHapus.setVisible(true);
            }
//            btnReset.setVisible(true);
        }
        
    }//GEN-LAST:event_tableJurusanMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM nilai WHERE id_nilai = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, selectedId);

            int rowsAffected = stat.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                initTable();
                reset();
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.moveToForm();  
        
        btnFormUpdate.setVisible(true);
        btnFormSave.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.moveToTable();
        this.reset();
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnFormSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSaveActionPerformed
        // TODO add your handling code here:
        if(validateInput()){
            this.insert();
            this.moveToTable();
        }else{
            JOptionPane.showMessageDialog(null, "Nama Atau Keterangan Kosong !!");
        }
    }//GEN-LAST:event_btnFormSaveActionPerformed

    private void btnFormUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUpdateActionPerformed
        // TODO add your handling code here:
        if(validateInput()){
            this.update();
            this.moveToTable();
        }else{
            JOptionPane.showMessageDialog(null, "Nama Atau Keterangan Kosong !!");
        }
    }//GEN-LAST:event_btnFormUpdateActionPerformed

    private void nilaiTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiTxtKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_nilaiTxtKeyTyped

    private void nilaiTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiTxtKeyReleased
        // TODO add your handling code here:
        int nilaiValue = 0;
        if(!nilaiTxt.getText().equals("")){
            try{
                nilaiValue = Integer.valueOf(nilaiTxt.getText());
            }catch(Exception e){
                System.err.println(e.getMessage());

                nilaiTxt.setText("0");
            }
            if(nilaiValue > 100){
                nilaiTxt.setText("100");
            }
        }
    }//GEN-LAST:event_nilaiTxtKeyReleased

    
    
    public boolean validateInput(){
        boolean res = false;
        String nama = namaTxt.getText();
        String ket = nilaiTxt.getText();
        
        if(!nama.equals("") && !ket.equals("")){
            res = true;
        }
        
        return res;
    }
    
    public void update(){
        String sql = "UPDATE nilai SET nama_jenis=?, nilai=? WHERE id_nilai=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, namaTxt.getText());
            stat.setString(2, nilaiTxt.getText());
            stat.setInt(3, selectedId);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiUpdate");
            initTable();
            reset();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
        }
    }
    public void insert(){
          String sql = "INSERT INTO nilai (nama_jenis, nilai, id_pendaftaran) VALUES (?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, namaTxt.getText());
            stat.setString(2, nilaiTxt.getText());
            stat.setInt(3, idPendaftaran);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            initTable();
            reset();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnFormSave;
    private javax.swing.JButton btnFormUpdate;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JLabel nilaiRata;
    private javax.swing.JTextField nilaiTxt;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTable tableJurusan;
    // End of variables declaration//GEN-END:variables
}
