/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author lincbp
 */
public class ReportPendaftaran extends javax.swing.JPanel {
    private List<Map.Entry<String, String>> listSiswa;
    private Connection conn = new koneksi().connect();
    /**
     * Creates new form ReportPendaftaran
     */
    public ReportPendaftaran() {
        initComponents();
        initSiswa();
    }

    public void initSiswa(){
        Map<String, String> map = new HashMap<>(); 
        String sql = "SELECT s.id_siswa, s.nama,s.nisn FROM siswa s RIGHT JOIN pendaftaran p ON s.id_siswa = p.id_siswa";
        comboSiswa.removeAllItems();
        comboSiswa.addItem("");
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                map.put(hasil.getString("id_siswa"), hasil.getString("nama")+" - "+hasil.getString("nisn"));
                comboSiswa.addItem(hasil.getString("nama")+" - "+hasil.getString("nisn"));
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        
        Set<Map.Entry<String, String> > set = map.entrySet();
        List<Map.Entry<String, String> > list = new ArrayList<>(set);
        listSiswa = list;
    }
    public int getSiswa(String nama){
        int res = 0;
        
        for(int i = 0; i<listSiswa.size(); i++){
            if(listSiswa.get(i).getValue().equals(nama)){
                res = Integer.valueOf(listSiswa.get(i).getKey());
                break;
            }
        }
        
        return res;
    }
    private void showReport(){
        HashMap a = new HashMap();
        int idSiswa = 0;
        if(comboSiswa.getSelectedIndex() > 0){
            idSiswa = getSiswa(comboSiswa.getSelectedItem().toString());
        }
        System.out.println(idSiswa);
        if(idSiswa > 0){
            a.put("idSiswa", idSiswa);
            try {
                File file = new File("src/report/ReportPendaftaranSiswa.jasper");
               JasperReport jr = (JasperReport) JRLoader.loadObject(file);
               JasperPrint jp = JasperFillManager.fillReport(jr, a, conn);
               JRViewer vw = new JRViewer(jp);
               jPanel1.removeAll();
               jPanel1.add(vw);
               jPanel1.repaint();
               jPanel1.revalidate();
               
//               JasperViewer.viewReport(jp, false);
//               JasperViewer.setDefaultLookAndFeelDecorated(true);        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboSiswa = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel2.setText("REPORT Pendaftaran");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Siswa : ");

        comboSiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSiswa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSiswaItemStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboSiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showReport();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboSiswaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSiswaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSiswaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
