/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author lincbp
 */
public class TagihanSiswa extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private int pendaftaranId;
    
    private int selectedId;
    /**
     * Creates new form TagihanSiswa
     */
    public TagihanSiswa(int id) {
        initComponents();
        this.pendaftaranId = id;
        getDataPembayaran();
        
        btnBayar.setVisible(false);
    }
    
    public void getDataPembayaran(){
        Object[] Baris={"Id","Nama Tagihan","Biaya","DiBayar"};
        tabmode = new DefaultTableModel(null, Baris){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        tableTagihan.setModel(tabmode);
        int totalTagihan = 0;
        int totalRow = 0;
        String sql = "select * from tagihan where id_pendaftaran = '"+pendaftaranId+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                int a = hasil.getInt("id_tagihan");
                String b = hasil.getString("nama_tagihan");
                String c = hasil.getString("biaya");
                String d = hasil.getString("dibayar");
                
                totalTagihan += (hasil.getDouble("biaya") - hasil.getDouble("dibayar"));
                Object[] data={a,b,c,d};
                tabmode.addRow(data);
            }
            
            
            this.sisaTagihan.setText("Total Tagihan : "+String.valueOf(totalTagihan));
        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    public void moveToTable(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelTable);
        cardLayout.repaint();
        cardLayout.revalidate();
    }
    
    public void moveToForm(){
        cardLayout.removeAll();
        cardLayout.repaint();
        cardLayout.revalidate();
        
        cardLayout.add(panelForm);
        cardLayout.repaint();
        cardLayout.revalidate();
    }
    
    public void reset(){
        btnBayar.setVisible(false);
        selectedId = 0;
        dibayarTxt.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLayout = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        sisaTagihan = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTagihan = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        biayaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        btnFormSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dibayarTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        cardLayout.setLayout(new java.awt.CardLayout());

        sisaTagihan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sisaTagihan.setText("jLabel1");

        btnBayar.setText("Bayar");
        btnBayar.setToolTipText("");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        jLabel2.setText("Tagihan");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableTagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTagihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTagihan);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTableLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(0, 585, Short.MAX_VALUE))
                        .addGroup(panelTableLayout.createSequentialGroup()
                            .addComponent(btnBayar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sisaTagihan)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sisaTagihan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        cardLayout.add(panelTable, "card2");

        panelForm.setLayout(new javax.swing.BoxLayout(panelForm, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        panelForm.add(jPanel2);

        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        mainPanel.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("FORM TAGIHAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Tagihan");

        namaTxt.setEditable(false);

        biayaTxt.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Biaya");

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnFormSave.setText("Save");
        btnFormSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Dibayar");

        dibayarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dibayarTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dibayarTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(biayaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dibayarTxt))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTxt))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFormSave)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(biayaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dibayarTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSave)
                    .addComponent(backBtn))
                .addGap(320, 320, 320))
        );

        panelForm.add(mainPanel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        panelForm.add(jPanel3);

        cardLayout.add(panelForm, "card3");

        add(cardLayout, "card4");
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        this.moveToForm();
    }//GEN-LAST:event_btnBayarActionPerformed
    
    private void tableTagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTagihanMouseClicked
        // TODO add your handling code here:
        int row = tableTagihan.getSelectedRow();

        if(row != -1){
            if(selectedId > 0 && selectedId == Integer.valueOf(tableTagihan.getValueAt(row, 0).toString())){
                this.reset();
            }else{
                String nama = tableTagihan.getValueAt(row, 1).toString();
                double biaya = Double.valueOf((String)tableTagihan.getValueAt(row, 2));
                double dibayarInt = 0.0;
                try{
                    String dibayar = (String)tableTagihan.getValueAt(row, 3);
                    if(dibayar.isEmpty() || dibayar.equals("")){
                        dibayarInt = 0.0;
                    }else{
                        dibayarInt = Double.valueOf(dibayar);
                    }
                }catch(Exception e){
                    
                }
                selectedId = Integer.valueOf(tableTagihan.getValueAt(row, 0).toString());
                if(biaya > dibayarInt){
                    btnBayar.setVisible(true);
                }else{
                    btnBayar.setVisible(false);
                }
                
                namaTxt.setText(nama);
                biayaTxt.setText(String.valueOf(biaya));
                dibayarTxt.setText(String.valueOf(dibayarInt));
//                namaTxt.setText(nama);
//                nilaiTxt.setText(keterangan);
//                btnTambah.setVisible(false);
//                btnUpdate.setVisible(true);
//                btnHapus.setVisible(true);
            }
            //            btnReset.setVisible(true);
        }

    }//GEN-LAST:event_tableTagihanMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void dibayarTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTxtKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_PERIOD )){
            evt.consume();
        }
    }//GEN-LAST:event_dibayarTxtKeyTyped

    private void dibayarTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dibayarTxtKeyReleased

    private void btnFormSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSaveActionPerformed
        // TODO add your handling code here:
        if(validateInput()){
            this.update();
            
            this.checkDataPembayaran();
            this.moveToTable();
        }
    }//GEN-LAST:event_btnFormSaveActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.moveToTable();
        this.reset();
    }//GEN-LAST:event_backBtnActionPerformed

    public void update(){
        String sql = "UPDATE tagihan SET dibayar=? WHERE id_tagihan=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, dibayarTxt.getText());
            stat.setInt(2, selectedId);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiUpdate");
            getDataPembayaran();
            this.moveToTable();
            reset();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
        }
    }
    
    public void checkDataPembayaran(){
        String sql = "SELECT SUM((biaya-dibayar)) as totalBiaya FROM tagihan WHERE id_pendaftaran= '"+pendaftaranId+"' AND (dibayar IS NULL OR dibayar < biaya)";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                int biaya = hasil.getInt("totalBiaya");
                if(biaya <= 0){
                    this.updateStatusPendaftaran();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Something Wrong.....");
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    public void updateStatusPendaftaran(){
        String sql = "UPDATE PENDAFTARAN SET status = 'Validasi Pembayaran' WHERE id_pendaftaran = ?";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setInt(1, pendaftaranId);

                int rowsAffected = stat.executeUpdate();

                if (!(rowsAffected > 0)) {
                    JOptionPane.showMessageDialog(null, "Something Wrong :' ");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
            }
    }
    
    public boolean validateInput(){
        boolean res = true;
        String message = "";
        
        double dibayar = 0.0;
        String dibayarString = dibayarTxt.getText();
        
        if(dibayarString.equals("")){
            message += "Field Dibayar Harus Diisi \n";
            res = false;
        }else{
            dibayar = Double.valueOf(dibayarTxt.getText());
            
            double biaya = Double.valueOf(biayaTxt.getText());
        
            if(dibayar > biaya){
                message += "Dibayar Tidak Boleh Lebih Besar Dari Biaya \n";
                res = false;
            }
        }
        
        if(!message.equals("")){
            JOptionPane.showMessageDialog(null, message);
        }
        
        return res;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField biayaTxt;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnFormSave;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JTextField dibayarTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelTable;
    private javax.swing.JLabel sisaTagihan;
    private javax.swing.JTable tableTagihan;
    // End of variables declaration//GEN-END:variables
}
